import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-black text-white relative`}
      >
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,#1a1a1a_0%,#181818_10%,#161616_20%,#141414_30%,#121212_40%,#101010_50%,#0e0e0e_60%,#0c0c0c_70%,transparent_100%)] pointer-events-none"></div>
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
